#=========================================================================
# TravisCI Setup
#=========================================================================

#------------------------------------------------------------------------
# language and build matrix
#------------------------------------------------------------------------

dist: xenial
language: python

python:
 - "3.7"

env:
 - CONFIG="-v --tb=short"

#------------------------------------------------------------------------
# install dependencies
#------------------------------------------------------------------------

install:

 # Install verilator
 - wget https://github.com/cornell-brg/verilator-travisci-cache/raw/master/verilator-travis-4.036.tar.gz
 - tar -C ${HOME} -xzf verilator-travis-4.036.tar.gz
 - export VERILATOR_ROOT=${HOME}/verilator
 - export PATH=${VERILATOR_ROOT}/bin:${PATH}
 - export PYMTL_VERILATOR_INCLUDE_DIR=${VERILATOR_ROOT}/share/verilator/include
 - verilator --version

 # Install PyMTL3
 - pip install -U git+https://github.com/pymtl/pymtl3.git@master --constraint constraints.txt
 - pip list

#------------------------------------------------------------------------
# test runner
#------------------------------------------------------------------------

script:
 - mkdir -p build
 - cd build
 - py.test ../ $CONFIG
 - py.test ../ $CONFIG --test-verilog

#-------------------------------------------------------------------------
# after success
#-------------------------------------------------------------------------
